TAG: "lithofacies_prediction_7.5_nnorm"
CUDNN_BENCHMARK: True
SEED: 654326212
DEVICE: "cuda"
GPUS: [ 1, 2, 3, 4 ]

PRETRAIN:
  LOAD: False
  TAG: "lithofacies_prediction_7.5"
  LOAD_EPOCH: 25
  LOAD_OPTIMIZER: True

DATASET:
  DATA_POOL: "southsea"
  VOLUME_TAG: "3dn_tbcut"
  FACIES_TAG: "3dn_facies_tbcut"
  TRAIN_BATCH_SIZE: 8
  VALID_BATCH_SIZE: 8
  TRAIN_IDX: [ 0, 2000 ]
  VALID_IDX: [ 2000, 2667 ]
  TRAIN_CROP_SIZE: [ 756, 512 ]
  VALID_CROP_SIZE: [ 756, 512 ]
  VDT: 12.5
  TDT: 7.5
  TRAIN_NUM_DATA: 4000
  VALID_NUM_DATA: 400
  FLIP: True
  NOISE: 0.01
  NUM_WORKER: 1

MODEL:
  A_CHANNELS: 1
  B_CHANNELS: 6
  INFO_CHANNELS: 1
  GEN_CHANNELS: 32
  GEN_NORM: False
  GEN_ATTN: True

TRAIN:
  BEGIN_EPOCH: 0
  END_EPOCH: 50
  CHECK_EPOCH: 1
  LR: 0.0001
  LR_EXP: 0.99
  BETA1: 0.9
  BETA2: 0.999

EVAL:
  BATCH_SIZE_FID: 28
  BEGIN_EPOCH: 300
  END_EPOCH: 500
  STEP_EPOCH: 10
